### ISSUE TITLE
Suggestion - add text-align:center to h1.caption to center it

### ISSUE THREAD

**Issue by jzhu01** [xecc0zpgith/prj-rev-bwfs-dasmoto#4]
Seen here: 
https://github.com/xecc0zpgith/prj-rev-bwfs-dasmoto/blob/2a9393efb99b528f7286a3b6be2743b165d8f1eb/DasmatoProj/resources/css/style.css#L8-L13
Since this is shifted to the left currently, I recommend centering it to follow the mock.
**Edit**: This is the text I am referring to: `text-align: center`. Hope this helps!

**Comment by xecc0zpgith** [comment]
Hi jzhu01,
Can you please add your recommended coding in your suggestion here. Am new to coding and still a long way to go in this online class playing catch up. Thank you very much.

**Comment by xecc0zpgith** [comment]
Hi jzhu01,
Can you please add the code in your suggestion. I have a long way to go in the course and I am still playing catch up. Thank you very much for your help....
